name : Run tests

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: windows-latest
        # checkout code
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        # set up env
        - name: Set up Python 3.x
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        # install dependencies 
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip 
            python.exe -m pip install -r PythonCerealAPI/requirements.txt
        # run tests
        - name: Run tests       
          run: |
            pytest Tests/tests.py --junitxml=Tests/test-results.xml --disable-warnings
                         
            
        # upload test resultss
        - name: Upload test results
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: Tests/test-results.xml
        
